config/routes.rb
Rails.application.routes.draw do
  # get 'books', to: 'books#index'
  root 'books#index'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    enum status: %w[Prestado Estante]

    # valida datos en blanco en el form
    validates :title, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: %i[show]
  before_action :set_selects, only: %i[new create]

  def index
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true)
  end

  def new
    @book = Book.new
  end

  def show
  end

  def create
    @book = Book.create(book_params)
    respond_to do |format|
      if @book.save
        format.html {redirect_to @book, notice: "El libro #{@book.title} ha sido creado exitosamente"}
      else
        format.html {render :new}
      end
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :status, :lend_date, :return_date)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def set_selects
    @statuses = Book.statuses.keys
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h1>El libro "<%= book.title %>" no ha sido creado por las siguientes razones:</h1>
      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <strong><%= f.label :title, "Titulo" %></strong>
    <%= f.text_field :title, placeholder: "Ingresa un Título", class: 'form-control' %>
  </div>

  <div class="form-group">
    <strong><%= f.label :author, "Autor" %></strong>
    <%= f.text_field :author, placeholder: "Ingresa un Autor", class: 'form-control' %>
  </div>

  <div class="form-group">
    <strong><%= f.label :status, "Estado" %></strong><br>
    <%= f.select :status, options_for_select(@statuses), class: 'form-control' %>
  </div>

  <div class="form-group">
    <strong><%= f.label :lend_date, "Fecha de Prestamo" %></strong>
    <%= f.date_field :lend_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <strong><%= f.label :return_date,"Fecha de Devolucion" %></strong>
    <%= f.date_field :return_date, class: 'form-control' %>
  </div>

  <div class='actions'>
    <%= submit_tag "Crear Libro", class: 'btn btn-success' %>
    <%= link_to 'Ver biblioteca', root_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/books/index.html.erb
<%= render 'shared/navbar' %>
<p id="notice"><%= notice %></p>

<h1>Mi Biblioteca</h1>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th><%= sort_link(@q, :title, 'Título') %></th>
        <th>Autor</th>
        <th>Estado</th>
        <th>Fecha de Préstamo</th>
        <th>Fecha de Devolución</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.status %></td>
          <td><%= book.lend_date %></td>
          <td><%= book.return_date %></td>
          <td><%= link_to 'Ver', book %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'Nuevo Libro', new_book_path, class: 'btn btn-success' %>

app/views/books/new.html.erb
<div class="container">
  <%= render 'form', book: @book %>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Libro consultado:</h1>
<p>
  <strong>Titulo: </strong>
  <%= @book.title %>
</p>
<p>
  <strong>Autor: </strong>
  <%= @book.author %>
</p>
<p>
  <strong>Estado: </strong>
  <%= @book.status %>
</p>
<p>
  <strong>Fecha de Préstamo: </strong>
  <%= @book.lend_date %>
</p>
<p>
  <strong>Fecha de Devolucion: </strong>
  <%= @book.return_date %>
</p>

<%= link_to 'Volver', root_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mi Biblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container pt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand"></a>
  <%= search_form_for @q do |f|%>
    <div class="form-group form-inline my-2 my-lg-0">
      <%= f.select :status_eq, options_for_select(Book.statuses, @q.status_eq), {}, {class: 'form-control mx-2'} %>
      <%= f.submit 'Filtrar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</nav>